### PR TITLE
fix uehaj2022 / latteart#21

### PR DESCRIPTION
**Pull request by kushagra20251**
**Confirmation dialog Box for pausing and resuming capture tool.**
adding a confirmation dialog box will make sure that there is no unwanted clicks on the pause button and same can be implemented for resuming the recording just as precautionary action

### CODE REVIEW

**Comment by kushagra20251** [comment]
respected sir,
The following PR contains changes for both issue 6 and issue 21. Kindly review If there is any modification required.
Thank you

**Comment by uehaj2022** [comment]
> The following PR contains changes for both issue 6 and issue 21. Kindly review If there is any modification required.
Thank you

it is not ideal to combine two issues. Can you separate PR for each issues?

**Comment by kushagra20251** [comment]
respected sir,
I pushed changes from forked branch and it contains fully updated code for both issue. I did that on purpose since changes are only UI based they can be resolved using one issue. If it is not suitable then I remove this issue and make a new one with only changes for issue 21 only. awaiting for a response.
thanks and regards

**Comment by kushagra20251** [comment]
kindly, ignore this closed PR as it contained both the issues 6 and 21. There is another PR with same names for the individual changes

**Comment by uehaj2022** [comment]
> kindly, ignore this closed PR as it contained both the issues 6 and 21. There is another PR with same names for the individual changes

Thank you for your response.
We understand.

**Pull request closed without merging**
