### PR TITLE
fix uehaj2022 / latteart#6

### PR DESCRIPTION
**Pull request by kushagra20251**
added code for issue 6 ( used only CSS so that JavaScript remains same and hence less trouble while merging)

### CODE REVIEW

**Comment by uehaj2022** [comment]
Tanks for PR and implementation.  
We think your work is good, but be wold like to comment at some point.
- please change name of pull request to "fix uehaj2022 / latteart#6" ("fix "+organization name+"/latteart#" + issue number).
- you might better to create new topic branch for each work.  branch name is free( for example, "issue/#6_changes_in_legend")
- the label string "legend" is not i18n. can you separate them into message file? in Japanse, "legend" is "凡例".
- We recommend to use UI component <v-expansion-panel-content> for accordion-like UI  instead of implement with css(sass). c.f. https://v15.vuetifyjs.com/en/components/expansion-panels/

**Comment by kushagra20251** [comment]
respected sir,

- I have fixed the name for the PR.
- I have changed the message file and it is now in both languages.
- I will make a new PR with changes into a new branch according to your suggestion.
- I tried it using vuetify expandable list view but it was not looking any better and there are some limitation with vuetify like adding a transition effect that I have given using CSS.
thanks and regards 
kushagra sharma

**Comment by uehaj2022** [comment]
Thank you sir,

> * I have fixed the name for the PR.

Thank you for change. it is OK.

> * I have changed the message file and it is now in both languages.

It looks good for me.

> * I will make a new PR with changes into a new branch according to your suggestion.

Thank you so much!

> * I tried it using vuetify expandable list view but it was not looking any better and there are some limitation with vuetify like adding a transition effect that I have given using CSS.

I'm sorry, I have missed for  component recomendation. We should to offer to examine  to use component for this usecase.
How about following component to use? please give us your opnion.

https://v15.vuetifyjs.com/en/components/bottom-navigation

**Comment by uehaj2022** [comment]
We choose git branch strategy to use so called "topic branch".
In this case, you had better to follow following steps for make PR.

(1) create new branch from main (ex. issue23_implement_some_dialog )
(2) commit changes on the branch "issue23_implement_some_dialog"
(3) create a PR that from topic branch(issue23_implement_some_dialog) to upstream main branch(uehaj2022/latteart:main).

I believe this way is de-facto standard way for using git, but this time some extra steps might be needed for redo the PR.
So I think it is ok in this time, but next time I'm happy if you  follow above "topic branch" way,
best regards.

**Comment by kushagra20251** [comment]
respected sir,
The vuetify component (link :https://v15.vuetifyjs.com/en/components/bottom-navigation) is not suitable for expanding legend feature it is more suitable for switching between multiple content. I might not be fully correct here but this is not suitable according to me , although i can impliment it if it is more recommeded here. hoping for a consideration.
thanks and regards

**Comment by kushagra20251** [comment]
kindly, ignore this closed PR as it contained both the issues 6 and 21. There is another PR with same names for the individual changes

**Comment by uehaj2022** [comment]
> kindly, ignore this closed PR as it contained both the issues 6 and 21. There is another PR with same names for the individual changes

respected sir,
Thank you for your response.
We understand.

**Pull request closed without merging**
